### ISSUE TITLE
Create admin repo

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/bootstrap#155] opened 2019-04-15 13:15 UTC
What should be included?

* Project progression
* Charter
* Code of Conduct
* Moderation Policy
* Mailing list policy

???

**Comment by obensource** [comment] 2019-04-30 22:35
@MylesBorins I concur that the suggestions you listed should be included in this repo, and beyond adding a license and readme – other documents we might consider are:
* Transferring a repo into the OpenJS org
* GitHub Org Management Policy
* Member Expectations
* Working Group Requirements

**Comment by obensource** [comment] 2019-05-06 06:42
🎉 WAHOO! 🎉

Seeded the [openjs-foundation/admin](https://github.com/openjs-foundation/admin) repo. Everyone in /bootstrap has admin access. Topped-off with [a few PRs](https://github.com/openjs-foundation/admin/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) and [issues](https://github.com/openjs-foundation/admin/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 👍

**Comment by obensource** [comment] 2019-05-06 06:45
👉 Looks like our member access privileges are set to read regardless, so in any case – everyone should have the access they need now. 🎷😎

**Comment by MylesBorins** [comment] 2019-05-06 16:17
In retrospect I'm not 100% if we need an admin repo, opened https://github.com/openjs-foundation/admin/issues/14

**Comment by obensource** [comment] 2019-05-06 18:37
After discussing [admin/#14](https://github.com/openjs-foundation/admin/issues/14), the bootstrap team determined in [today's meeting](https://github.com/openjs-foundation/bootstrap/issues/168) that the [admin](https://github.com/openjs-foundation/admin) repository isn't relevant at this time as we only have one Top Level Committee and we'll be renaming the bootstrap repo to `cross-project-council` soon – which will handle any concerns the admin repo was intended to address.

I'll be deleting the existing admin repo and migrating any relevant issues to the /bootstrap repository.

Given the above, I'm closing this issue. 👍

**Closed by obensource** 2019-05-06 18:37 UTC

**Comment by obensource** [comment] 2019-05-06 18:51
![deleted](https://i.kym-cdn.com/entries/icons/mobile/000/017/316/S7xEtpr.jpg)
